server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: spring
    password: spring
    hikari:
      auto-commit: false
      data-source-properties:
        useSSL:         false
  flyway:
    fail-on-missing-locations: true

logging:
  level:
    '[jp.mirageworld.spring]': trace