version: '3'

services:

    db:
        image: mysql:8
        ports:
            -   3306:3306
        environment: 
            MYSQL_ROOT_PASSWORD: spring
            MYSQL_DATABASE:      spring
            MYSQL_USER:          spring
            MYSQL_PASSWORD:      spring
        command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
        volumes: 
            -   /var/lib/mysql

    adminer:
        image: adminer
        ports:
            -   9101:8080
